stages:
  - env-creation
  - prepare-${{values.awsEnvironmentName}}-stage

variables:
  APP_SHORT_NAME: "${{ values.component_id }}"
  APP_TEMPLATE_NAME: "example-generic"
  OPA_PLATFORM_REGION: "${{ values.platformRegion }}"

include:
  - remote: 'https://raw.githubusercontent.com/csna-projects/harmonix/dev/backstage-reference/common/cicd/.gitlab-ci-job-defaults-cdk.yml'
  - remote: 'https://raw.githubusercontent.com/csna-projects/harmonix/dev/backstage-reference/common/cicd/.gitlab-ci-aws-base.yml'
  - remote: 'https://raw.githubusercontent.com/csna-projects/harmonix/dev/backstage-reference/common/cicd/.gitlab-ci-aws-iac-secretsmanager.yml'
