stages:
  - env-creation
  - prepare-${{values.awsEnvironmentName}}-stage
  - ${{values.awsEnvironmentName}}-stage

variables:
  APP_KEBAB_NAME: "${{ values.kebabName }}"
  APP_SHORT_NAME: "${{ values.component_id }}"
  APP_TEMPLATE_NAME: "example-serverless-rest-api"
  OPA_PLATFORM_REGION: "${{ values.platformRegion }}"

include:
  - remote: 'https://raw.githubusercontent.com/csna-projects/harmonix/generalise-changes/backstage-reference/common/cicd/.gitlab-ci-job-defaults-cdk.yml'
  - remote: 'https://raw.githubusercontent.com/csna-projects/harmonix/generalise-changes/backstage-reference/common/cicd/.gitlab-ci-aws-base.yml'
  - remote: 'https://raw.githubusercontent.com/csna-projects/harmonix/generalise-changes/backstage-reference/common/cicd/.gitlab-ci-aws-iac-serverless-api.yml'
