image: node:18

variables:
  AWS_ACCOUNT: "${{ values.awsAccount }}"
  AWS_DEFAULT_REGION: "${{ values.awsRegion }}"
  ROLE_ARN: "${{ values.environmentRole }}"
  OPA_PLATFORM_REGION: "${{ values.platformRegion }}"
  
stages:
  - build
  
include:
  - remote: 'https://raw.githubusercontent.com/csna-projects/harmonix/generalise-changes/backstage-reference/common/cicd/.gitlab-ci-aws-provider-ecs.yml'
